In [2]:
import pandas as pd

In [ ]:
path = "../data/en.openfoodfacts.org.products.csv/en.openfoodfacts.org.products.csv"
df = pd.read_csv(path, nrows=100, sep='\t', encoding="utf-8")

:

:

:

:

In [ ]:
df

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g
0,2,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1760861583,2025-10-19T08:13:03Z,1760861586,2025-10-19T08:13:06Z,NaN,1760861586,2025-10-19T08:13:06Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1752485388,2025-07-14T09:29:48Z,1752485389,2025-07-14T09:29:49Z,NaN,1752485389,2025-07-14T09:29:49Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1768903196,2026-01-20T09:59:56Z,1768903204,2026-01-20T10:00:04Z,NaN,1768903204,2026-01-20T10:00:04Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,http://world-en.openfoodfacts.org/product/0000...,moon-rabbit,1767072228,2025-12-30T05:23:48Z,1767072233,2025-12-30T05:23:53Z,moon-rabbit,1767072233,2025-12-30T05:23:53Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,http://world-en.openfoodfacts.org/product/0000...,moon-rabbit,1760212975,2025-10-11T20:02:55Z,1760218930,2025-10-11T21:42:10Z,ascharao,1760218930,2025-10-11T21:42:10Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,98,http://world-en.openfoodfacts.org/product/0000...,ptitof35,1559383944,2019-06-01T10:12:24Z,1727965061,2024-10-03T14:17:41Z,fix-code-bot,1743160951,2025-03-28T11:22:31Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,99,http://world-en.openfoodfacts.org/product/0000...,elcoco,1566888090,2019-08-27T06:41:30Z,1730038053,2024-10-27T14:07:33Z,smoothie-app,1743690944,2025-04-03T14:35:44Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,100,http://world-en.openfoodfacts.org/product/0000...,del51,1444572561,2015-10-11T14:09:21Z,1737486361,2025-01-21T19:06:01Z,NaN,1743522369,2025-04-01T15:46:09Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,101,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1568746303,2019-09-17T18:51:43Z,1736848791,2025-01-14T09:59:51Z,prepperapp,1743319994,2025-03-30T07:33:14Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,102,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1619332243,2021-04-25T06:30:43Z,1742127536,2025-03-16T12:18:56Z,bot-tags-and-languages,1743288970,2025-03-29T22:56:10Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

:

:

:

:

In [ ]:
df.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 209 columns):
 #    Column                            Dtype
---   ------                            -----
 0    code                              int64
 1    url                               object
 2    creator                           object
 3    created_t                         int64
 4    created_datetime                  object
 5    last_modified_t                   int64
 6    last_modified_datetime            object
 7    last_modified_by                  object
 8    last_updated_t                    int64
 9    last_updated_datetime             object
 10   product_name                      object
 11   abbreviated_product_name          float64
 12   generic_name                      object
 13   quantity                          object
 14   packaging                         object
 15   packaging_tags                    object
 16   packaging_en                      object
 17   packaging_text                    float64
 18   brands                            object
 19   brands_tags                       object
 20   brands_en                         object
 21   categories                        object
 22   categories_tags                   object
 23   categories_en                     object
 24   origins                           object
 25   origins_tags                      object
 26   origins_en                        object
 27   manufacturing_places              object
 28   manufacturing_places_tags         object
 29   labels                            object
 30   labels_tags                       object
 31   labels_en                         object
 32   emb_codes                         object
 33   emb_codes_tags                    object
 34   first_packaging_code_geo          object
 35   cities                            float64
 36   cities_tags                       object
 37   purchase_places                   object
 38   stores                            object
 39   countries                         object
 40   countries_tags                    object
 41   countries_en                      object
 42   ingredients_text                  object
 43   ingredients_tags                  object
 44   ingredients_analysis_tags         object
 45   allergens                         object
 46   allergens_en                      float64
 47   traces                            object
 48   traces_tags                       object
 49   traces_en                         object
 50   serving_size                      object
 51   serving_quantity                  float64
 52   no_nutrition_data                 object
 53   additives_n                       float64
 54   additives                         float64
 55   additives_tags                    object
 56   additives_en                      object
 57   nutriscore_score                  float64
 58   nutriscore_grade                  object
 59   nova_group                        float64
 60   pnns_groups_1                     object
 61   pnns_groups_2                     object
 62   food_groups                       object
 63   food_groups_tags                  object
 64   food_groups_en                    object
 65   states                            object
 66   states_tags                       object
 67   states_en                         object
 68   brand_owner                       float64
 69   environmental_score_score         float64
 70   environmental_score_grade         object
 71   nutrient_levels_tags              object
 72   product_quantity                  float64
 73   owner                             object
 74   data_quality_errors_tags          object
 75   unique_scans_n                    float64
 76   popularity_tags                   object
 77   completeness                      float64
 78   last_image_t                      float64
 79   last_image_datetime               object
 80   main_category                     object
 81   main_category_en                  object
 82   image_url                         object
 83   image_small_url                   object
 84   image_ingredients_url             object
 85   image_ingredients_small_url       object
 86   image_nutrition_url               object
 87   image_nutrition_small_url         object
 88   energy-kj_100g                    float64
 89   energy-kcal_100g                  float64
 90   energy_100g                       float64
 91   energy-from-fat_100g              float64
 92   fat_100g                          float64
 93   saturated-fat_100g                float64
 94   butyric-acid_100g                 float64
 95   caproic-acid_100g                 float64
 96   caprylic-acid_100g                float64
 97   capric-acid_100g                  float64
 98   lauric-acid_100g                  float64
 99   myristic-acid_100g                float64
 100  palmitic-acid_100g                float64
 101  stearic-acid_100g                 float64
 102  arachidic-acid_100g               float64
 103  behenic-acid_100g                 float64
 104  lignoceric-acid_100g              float64
 105  cerotic-acid_100g                 float64
 106  montanic-acid_100g                float64
 107  melissic-acid_100g                float64
 108  unsaturated-fat_100g              float64
 109  monounsaturated-fat_100g          float64
 110  omega-9-fat_100g                  float64
 111  polyunsaturated-fat_100g          float64
 112  omega-3-fat_100g                  float64
 113  omega-6-fat_100g                  float64
 114  alpha-linolenic-acid_100g         float64
 115  eicosapentaenoic-acid_100g        float64
 116  docosahexaenoic-acid_100g         float64
 117  linoleic-acid_100g                float64
 118  arachidonic-acid_100g             float64
 119  gamma-linolenic-acid_100g         float64
 120  dihomo-gamma-linolenic-acid_100g  float64
 121  oleic-acid_100g                   float64
 122  elaidic-acid_100g                 float64
 123  gondoic-acid_100g                 float64
 124  mead-acid_100g                    float64
 125  erucic-acid_100g                  float64
 126  nervonic-acid_100g                float64
 127  trans-fat_100g                    float64
 128  cholesterol_100g                  float64
 129  carbohydrates_100g                float64
 130  sugars_100g                       float64
 131  added-sugars_100g                 float64
 132  sucrose_100g                      float64
 133  glucose_100g                      float64
 134  fructose_100g                     float64
 135  galactose_100g                    float64
 136  lactose_100g                      float64
 137  maltose_100g                      float64
 138  maltodextrins_100g                float64
 139  psicose_100g                      float64
 140  starch_100g                       float64
 141  polyols_100g                      float64
 142  erythritol_100g                   float64
 143  isomalt_100g                      float64
 144  maltitol_100g                     float64
 145  sorbitol_100g                     float64
 146  fiber_100g                        float64
 147  soluble-fiber_100g                float64
 148  polydextrose_100g                 float64
 149  insoluble-fiber_100g              float64
 150  proteins_100g                     float64
 151  casein_100g                       float64
 152  serum-proteins_100g               float64
 153  nucleotides_100g                  float64
 154  salt_100g                         float64
 155  added-salt_100g                   float64
 156  sodium_100g                       float64
 157  alcohol_100g                      float64
 158  vitamin-a_100g                    float64
 159  beta-carotene_100g                float64
 160  vitamin-d_100g                    float64
 161  vitamin-e_100g                    float64
 162  vitamin-k_100g                    float64
 163  vitamin-c_100g                    float64
 164  vitamin-b1_100g                   float64
 165  vitamin-b2_100g                   float64
 166  vitamin-pp_100g                   float64
 167  vitamin-b6_100g                   float64
 168  vitamin-b9_100g                   float64
 169  folates_100g                      float64
 170  vitamin-b12_100g                  float64
 171  biotin_100g                       float64
 172  pantothenic-acid_100g             float64
 173  silica_100g                       float64
 174  bicarbonate_100g                  float64
 175  potassium_100g                    float64
 176  chloride_100g                     float64
 177  calcium_100g                      float64
 178  phosphorus_100g                   float64
 179  iron_100g                         float64
 180  magnesium_100g                    float64
 181  zinc_100g                         float64
 182  copper_100g                       float64
 183  manganese_100g                    float64
 184  fluoride_100g                     float64
 185  selenium_100g                     float64
 186  chromium_100g                     float64
 187  molybdenum_100g                   float64
 188  iodine_100g                       float64
 189  caffeine_100g                     float64
 190  taurine_100g                      float64
 191  methylsulfonylmethane_100g        float64
 192  ph_100g                           float64
 193  fruits-vegetables-legumes_100g    float64
 194  collagen-meat-protein-ratio_100g  float64
 195  cocoa_100g                        float64
 196  chlorophyl_100g                   float64
 197  carbon-footprint_100g             float64
 198  glycemic-index_100g               float64
 199  water-hardness_100g               float64
 200  choline_100g                      float64
 201  phylloquinone_100g                float64
 202  beta-glucan_100g                  float64
 203  inositol_100g                     float64
 204  carnitine_100g                    float64
 205  sulphate_100g                     float64
 206  nitrate_100g                      float64
 207  acidity_100g                      float64
 208  carbohydrates-total_100g          float64
dtypes: float64(136), int64(4), object(69)
memory usage: 163.4+ KB

:

:

:

:

In [ ]:
# Variables les plus corrélées au Nutri-Score et à l'Eco-Score
import numpy as np

# Candidats de colonnes cibles (OpenFoodFacts peut varier selon version)
nutri_candidates = ["nutriscore_score", "nutrition-score-fr_100g", "nutriscore"]
eco_candidates = ["ecoscore_score", "ecoscore_data.grade", "ecoscore"]

def pick_existing_column(candidates, columns):
    for c in candidates:
        if c in columns:
            return c
    return None

nutri_col = pick_existing_column(nutri_candidates, df.columns)
eco_col = pick_existing_column(eco_candidates, df.columns)

def show_strongest_correlations(target_col, data, min_periods=5):
    if target_col is None:
        print("Colonne cible introuvable.")
        return

    # Garder uniquement les variables numériques
    num_df = data.select_dtypes(include=[np.number]).copy()

    # Au cas où la cible est en texte mais convertible en nombre
    if target_col not in num_df.columns and target_col in data.columns:
        converted = pd.to_numeric(data[target_col], errors="coerce")
        num_df[target_col] = converted

    if target_col not in num_df.columns:
        print(f"La colonne '{target_col}' n'est pas numérique et n'a pas pu être convertie.")
        return

    corr_matrix = num_df.corr(numeric_only=True, min_periods=min_periods)
    if target_col not in corr_matrix.columns:
        print("Impossible de calculer les corrélations pour cette cible (données insuffisantes).")
        return

    corr = corr_matrix[target_col].dropna().drop(labels=[target_col], errors="ignore")
    if corr.empty:
        print("Aucune variable corrélée calculable avec les paramètres actuels.")
        return

    result = pd.DataFrame({
        "correlation": corr,
        "correlation_abs": corr.abs()
    }).sort_values(["correlation_abs", "correlation"], ascending=[False, False])

    max_corr = result["correlation_abs"].max()
    strongest = result[np.isclose(result["correlation_abs"], max_corr)]

    print(f"\nVariable(s) LES PLUS corrélée(s) à '{target_col}' (|corr| max = {max_corr:.4f}) :")
    display(strongest)

    print("\nClassement complet (trié par corrélation absolue décroissante) :")
    display(result)

print(f"Colonne Nutri-Score utilisée : {nutri_col}")
show_strongest_correlations(nutri_col, df)

print(f"\nColonne Eco-Score utilisée : {eco_col}")
show_strongest_correlations(eco_col, df)

Colonne Nutri-Score utilisée : nutriscore_score

Top 15 variables corrélées à 'nutriscore_score' :

                           correlation  correlation_abs
environmental_score_score    -0.478611         0.478611
last_image_t                  0.282933         0.282933
last_updated_t               -0.250625         0.250625
product_quantity              0.203863         0.203863
completeness                  0.155171         0.155171
code                          0.146941         0.146941
nova_group                    0.128811         0.128811
serving_quantity             -0.100111         0.100111
additives_n                   0.089867         0.089867
unique_scans_n                0.066886         0.066886
created_t                    -0.013632         0.013632
last_modified_t               0.006260         0.006260

Colonne Eco-Score utilisée : None
Colonne cible introuvable.

:

:

:

: