In [1]:
import pandas as pd
import numpy as np

In [4]:
path = "/Users/thomas/Documents/GitHub/ML-Nutriscore/data/en.openfoodfacts.org.products.csv"
df = pd.read_csv(path, nrows=100, sep='\t',encoding="utf-8")

In [5]:
df

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,water-hardness_100g,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g
0,2,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1760861583,2025-10-19T08:13:03Z,1760861586,2025-10-19T08:13:06Z,NaN,1760861586,2025-10-19T08:13:06Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1752485388,2025-07-14T09:29:48Z,1752485389,2025-07-14T09:29:49Z,NaN,1752485389,2025-07-14T09:29:49Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1768903196,2026-01-20T09:59:56Z,1768903204,2026-01-20T10:00:04Z,NaN,1768903204,2026-01-20T10:00:04Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,http://world-en.openfoodfacts.org/product/0000...,moon-rabbit,1767072228,2025-12-30T05:23:48Z,1767072233,2025-12-30T05:23:53Z,moon-rabbit,1767072233,2025-12-30T05:23:53Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6,http://world-en.openfoodfacts.org/product/0000...,moon-rabbit,1760212975,2025-10-11T20:02:55Z,1760218930,2025-10-11T21:42:10Z,ascharao,1760218930,2025-10-11T21:42:10Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,98,http://world-en.openfoodfacts.org/product/0000...,ptitof35,1559383944,2019-06-01T10:12:24Z,1727965061,2024-10-03T14:17:41Z,fix-code-bot,1743160951,2025-03-28T11:22:31Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,99,http://world-en.openfoodfacts.org/product/0000...,elcoco,1566888090,2019-08-27T06:41:30Z,1730038053,2024-10-27T14:07:33Z,smoothie-app,1743690944,2025-04-03T14:35:44Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,100,http://world-en.openfoodfacts.org/product/0000...,del51,1444572561,2015-10-11T14:09:21Z,1737486361,2025-01-21T19:06:01Z,NaN,1743522369,2025-04-01T15:46:09Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,101,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1568746303,2019-09-17T18:51:43Z,1736848791,2025-01-14T09:59:51Z,prepperapp,1743319994,2025-03-30T07:33:14Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,102,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1619332243,2021-04-25T06:30:43Z,1742127536,2025-03-16T12:18:56Z,bot-tags-and-languages,1743288970,2025-03-29T22:56:10Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
print(f"Nombre de colonnes : {len(df.columns)}")
print(df.columns.tolist())

Nombre de colonnes : 209
['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime', 'last_modified_by', 'last_updated_t', 'last_updated_datetime', 'product_name', 'abbreviated_product_name', 'generic_name', 'quantity', 'packaging', 'packaging_tags', 'packaging_en', 'packaging_text', 'brands', 'brands_tags', 'brands_en', 'categories', 'categories_tags', 'categories_en', 'origins', 'origins_tags', 'origins_en', 'manufacturing_places', 'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en', 'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities', 'cities_tags', 'purchase_places', 'stores', 'countries', 'countries_tags', 'countries_en', 'ingredients_text', 'ingredients_tags', 'ingredients_analysis_tags', 'allergens', 'allergens_en', 'traces', 'traces_tags', 'traces_en', 'serving_size', 'serving_quantity', 'no_nutrition_data', 'additives_n', 'additives', 'additives_tags', 'additives_en', 'nutriscore_score', 'nutriscore_grade', 'nova_group', 'pnns_groups_1', 'pnns_groups_2', 'food_groups', 'food_groups_tags', 'food_groups_en', 'states', 'states_tags', 'states_en', 'brand_owner', 'environmental_score_score', 'environmental_score_grade', 'nutrient_levels_tags', 'product_quantity', 'owner', 'data_quality_errors_tags', 'unique_scans_n', 'popularity_tags', 'completeness', 'last_image_t', 'last_image_datetime', 'main_category', 'main_category_en', 'image_url', 'image_small_url', 'image_ingredients_url', 'image_ingredients_small_url', 'image_nutrition_url', 'image_nutrition_small_url', 'energy-kj_100g', 'energy-kcal_100g', 'energy_100g', 'energy-from-fat_100g', 'fat_100g', 'saturated-fat_100g', 'butyric-acid_100g', 'caproic-acid_100g', 'caprylic-acid_100g', 'capric-acid_100g', 'lauric-acid_100g', 'myristic-acid_100g', 'palmitic-acid_100g', 'stearic-acid_100g', 'arachidic-acid_100g', 'behenic-acid_100g', 'lignoceric-acid_100g', 'cerotic-acid_100g', 'montanic-acid_100g', 'melissic-acid_100g', 'unsaturated-fat_100g', 'monounsaturated-fat_100g', 'omega-9-fat_100g', 'polyunsaturated-fat_100g', 'omega-3-fat_100g', 'omega-6-fat_100g', 'alpha-linolenic-acid_100g', 'eicosapentaenoic-acid_100g', 'docosahexaenoic-acid_100g', 'linoleic-acid_100g', 'arachidonic-acid_100g', 'gamma-linolenic-acid_100g', 'dihomo-gamma-linolenic-acid_100g', 'oleic-acid_100g', 'elaidic-acid_100g', 'gondoic-acid_100g', 'mead-acid_100g', 'erucic-acid_100g', 'nervonic-acid_100g', 'trans-fat_100g', 'cholesterol_100g', 'carbohydrates_100g', 'sugars_100g', 'added-sugars_100g', 'sucrose_100g', 'glucose_100g', 'fructose_100g', 'galactose_100g', 'lactose_100g', 'maltose_100g', 'maltodextrins_100g', 'psicose_100g', 'starch_100g', 'polyols_100g', 'erythritol_100g', 'isomalt_100g', 'maltitol_100g', 'sorbitol_100g', 'fiber_100g', 'soluble-fiber_100g', 'polydextrose_100g', 'insoluble-fiber_100g', 'proteins_100g', 'casein_100g', 'serum-proteins_100g', 'nucleotides_100g', 'salt_100g', 'added-salt_100g', 'sodium_100g', 'alcohol_100g', 'vitamin-a_100g', 'beta-carotene_100g', 'vitamin-d_100g', 'vitamin-e_100g', 'vitamin-k_100g', 'vitamin-c_100g', 'vitamin-b1_100g', 'vitamin-b2_100g', 'vitamin-pp_100g', 'vitamin-b6_100g', 'vitamin-b9_100g', 'folates_100g', 'vitamin-b12_100g', 'biotin_100g', 'pantothenic-acid_100g', 'silica_100g', 'bicarbonate_100g', 'potassium_100g', 'chloride_100g', 'calcium_100g', 'phosphorus_100g', 'iron_100g', 'magnesium_100g', 'zinc_100g', 'copper_100g', 'manganese_100g', 'fluoride_100g', 'selenium_100g', 'chromium_100g', 'molybdenum_100g', 'iodine_100g', 'caffeine_100g', 'taurine_100g', 'methylsulfonylmethane_100g', 'ph_100g', 'fruits-vegetables-legumes_100g', 'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g', 'carbon-footprint_100g', 'glycemic-index_100g', 'water-hardness_100g', 'choline_100g', 'phylloquinone_100g', 'beta-glucan_100g', 'inositol_100g', 'carnitine_100g', 'sulphate_100g', 'nitrate_100g', 'acidity_100g', 'carbohydrates-total_100g']

In [7]:
missing_percent_full = df.isna().mean().sort_values(ascending=False) * 100

missing_percent_full

lignoceric-acid_100g    100.0
cerotic-acid_100g       100.0
glucose_100g            100.0
fructose_100g           100.0
galactose_100g          100.0
                        ...
states                    0.0
states_tags               0.0
states_en                 0.0
completeness              0.0
code                      0.0
Length: 209, dtype: float64

In [8]:
nutrition_cols = [col for col in df.columns if "100g" in col]

missing_nutrition = missing_percent_full[missing_percent_full.index.isin(nutrition_cols)]

missing_nutrition.sort_values(ascending=False).head(209)

lignoceric-acid_100g         100.0
ph_100g                      100.0
vitamin-b9_100g              100.0
vitamin-b6_100g              100.0
vitamin-pp_100g              100.0
                             ...
alpha-linolenic-acid_100g    100.0
omega-6-fat_100g             100.0
omega-3-fat_100g             100.0
polyunsaturated-fat_100g     100.0
caproic-acid_100g            100.0
Length: 121, dtype: float64

In [9]:
# Colonnes avec Nutriscore dispo
df = df[df["nutriscore_grade"].notna()].copy()
print(df.shape)
print(df["nutriscore_grade"].value_counts(dropna=False))

(88, 209)
nutriscore_grade
unknown           59
not-applicable    10
a                  6
c                  5
e                  5
d                  3
Name: count, dtype: int64

In [10]:
# Nutriscore > variable numérique
mapping = {"a": 0, "b": 1, "c": 2, "d": 3, "e": 4}
df["target"] = df["nutriscore_grade"].str.lower().map(mapping)

print(df["target"].value_counts().sort_index())
df[["nutriscore_grade", "target"]].head()

target
0.0    6
2.0    5
3.0    3
4.0    5
Name: count, dtype: int64

  nutriscore_grade  target
5          unknown     NaN
6                c     2.0
7                c     2.0
8          unknown     NaN
9                a     0.0

In [12]:
# valeurs manquantes 
missing_percent = path.isna().mean().sort_values(ascending=False) * 100
missing_percent

AttributeError: 'str' object has no attribute 'isna'

In [13]:
df.head()

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g,target
5,6666,http://world-en.openfoodfacts.org/product/0000...,prepperapp,1709219541,2024-02-29T15:12:21Z,1759514643,2025-10-03T18:04:03Z,foodless,1771287398,2026-02-17T00:16:38Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,http://world-en.openfoodfacts.org/product/0000...,smoothie-app,1678803019,2023-03-14T14:10:19Z,1748262529,2025-05-26T12:28:49Z,smoothie-app,1748262529,2025-05-26T12:28:49Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
7,8,http://world-en.openfoodfacts.org/product/0000...,halal-app-chakib,1609862762,2021-01-05T16:06:02Z,1746874519,2025-05-10T10:55:19Z,roboto-app,1746874519,2025-05-10T10:55:19Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
8,9,http://world-en.openfoodfacts.org/product/0000...,prepperapp,1677761447,2023-03-02T12:50:47Z,1727982393,2024-10-03T19:06:33Z,maldan,1727982393,2024-10-03T19:06:33Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,http://world-en.openfoodfacts.org/product/0000...,openfoodfacts-contributors,1527242583,2018-05-25T10:03:03Z,1749674566,2025-06-11T20:42:46Z,smoothie-app,1749674566,2025-06-11T20:42:46Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [51]:
print(df.columns.tolist())

['code', 'url', 'creator', 'created_t', 'created_datetime', 'last_modified_t', 'last_modified_datetime', 'last_modified_by', 'last_updated_t', 'last_updated_datetime', 'product_name', 'abbreviated_product_name', 'generic_name', 'quantity', 'packaging', 'packaging_tags', 'packaging_en', 'packaging_text', 'brands', 'brands_tags', 'brands_en', 'categories', 'categories_tags', 'categories_en', 'origins', 'origins_tags', 'origins_en', 'manufacturing_places', 'manufacturing_places_tags', 'labels', 'labels_tags', 'labels_en', 'emb_codes', 'emb_codes_tags', 'first_packaging_code_geo', 'cities', 'cities_tags', 'purchase_places', 'stores', 'countries', 'countries_tags', 'countries_en', 'ingredients_text', 'ingredients_tags', 'ingredients_analysis_tags', 'allergens', 'allergens_en', 'traces', 'traces_tags', 'traces_en', 'serving_size', 'serving_quantity', 'no_nutrition_data', 'additives_n', 'additives', 'additives_tags', 'additives_en', 'nutriscore_score', 'nutriscore_grade', 'nova_group', 'pnns_groups_1', 'pnns_groups_2', 'food_groups', 'food_groups_tags', 'food_groups_en', 'states', 'states_tags', 'states_en', 'brand_owner', 'environmental_score_score', 'environmental_score_grade', 'nutrient_levels_tags', 'product_quantity', 'owner', 'data_quality_errors_tags', 'unique_scans_n', 'popularity_tags', 'completeness', 'last_image_t', 'last_image_datetime', 'main_category', 'main_category_en', 'image_url', 'image_small_url', 'image_ingredients_url', 'image_ingredients_small_url', 'image_nutrition_url', 'image_nutrition_small_url', 'energy-kj_100g', 'energy-kcal_100g', 'energy_100g', 'energy-from-fat_100g', 'fat_100g', 'saturated-fat_100g', 'butyric-acid_100g', 'caproic-acid_100g', 'caprylic-acid_100g', 'capric-acid_100g', 'lauric-acid_100g', 'myristic-acid_100g', 'palmitic-acid_100g', 'stearic-acid_100g', 'arachidic-acid_100g', 'behenic-acid_100g', 'lignoceric-acid_100g', 'cerotic-acid_100g', 'montanic-acid_100g', 'melissic-acid_100g', 'unsaturated-fat_100g', 'monounsaturated-fat_100g', 'omega-9-fat_100g', 'polyunsaturated-fat_100g', 'omega-3-fat_100g', 'omega-6-fat_100g', 'alpha-linolenic-acid_100g', 'eicosapentaenoic-acid_100g', 'docosahexaenoic-acid_100g', 'linoleic-acid_100g', 'arachidonic-acid_100g', 'gamma-linolenic-acid_100g', 'dihomo-gamma-linolenic-acid_100g', 'oleic-acid_100g', 'elaidic-acid_100g', 'gondoic-acid_100g', 'mead-acid_100g', 'erucic-acid_100g', 'nervonic-acid_100g', 'trans-fat_100g', 'cholesterol_100g', 'carbohydrates_100g', 'sugars_100g', 'added-sugars_100g', 'sucrose_100g', 'glucose_100g', 'fructose_100g', 'galactose_100g', 'lactose_100g', 'maltose_100g', 'maltodextrins_100g', 'psicose_100g', 'starch_100g', 'polyols_100g', 'erythritol_100g', 'isomalt_100g', 'maltitol_100g', 'sorbitol_100g', 'fiber_100g', 'soluble-fiber_100g', 'polydextrose_100g', 'insoluble-fiber_100g', 'proteins_100g', 'casein_100g', 'serum-proteins_100g', 'nucleotides_100g', 'salt_100g', 'added-salt_100g', 'sodium_100g', 'alcohol_100g', 'vitamin-a_100g', 'beta-carotene_100g', 'vitamin-d_100g', 'vitamin-e_100g', 'vitamin-k_100g', 'vitamin-c_100g', 'vitamin-b1_100g', 'vitamin-b2_100g', 'vitamin-pp_100g', 'vitamin-b6_100g', 'vitamin-b9_100g', 'folates_100g', 'vitamin-b12_100g', 'biotin_100g', 'pantothenic-acid_100g', 'silica_100g', 'bicarbonate_100g', 'potassium_100g', 'chloride_100g', 'calcium_100g', 'phosphorus_100g', 'iron_100g', 'magnesium_100g', 'zinc_100g', 'copper_100g', 'manganese_100g', 'fluoride_100g', 'selenium_100g', 'chromium_100g', 'molybdenum_100g', 'iodine_100g', 'caffeine_100g', 'taurine_100g', 'methylsulfonylmethane_100g', 'ph_100g', 'fruits-vegetables-legumes_100g', 'collagen-meat-protein-ratio_100g', 'cocoa_100g', 'chlorophyl_100g', 'carbon-footprint_100g', 'glycemic-index_100g', 'water-hardness_100g', 'choline_100g', 'phylloquinone_100g', 'beta-glucan_100g', 'inositol_100g', 'carnitine_100g', 'sulphate_100g', 'nitrate_100g', 'acidity_100g', 'carbohydrates-total_100g', 'target']